apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: git
  name: gitlab-runner-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "secrets"]
  verbs: ["get", "list", "watch", "create", "delete", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "delete", "patch"]
