apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: word-deploy-hpa
  namespace: word
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: word-deploy
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 2
        periodSeconds: 120
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 4
        periodSeconds: 120
      - type: Percent
        value: 50
        periodSeconds: 60
