namespace: word
replicaCount: 1

kind:
  deploy: Deployment
  service: Service

redis:
  name: redis
  image: redis
  version: latest
  port: 6379
  service: redis-service
  deploy: redis-deploy

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

service:
  port: 6379
  type: ClusterIP
  protocol: TCP

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
