apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-operator
commonAnnotations:
  operator.min.io/authors: "MinIO, Inc."
  operator.min.io/license: "Enterprise"
  operator.min.io/support: "https://subnet.min.io"
  operator.min.io/version: v5.0.13
  enterprise.min.io/version: RELEASE.2024-04-12T17-44-35Z

resources:
  - base/namespace.yaml
  - base/service-account.yaml
  - base/cluster-role.yaml
  - base/cluster-role-binding.yaml
  - base/crds/
  - base/service.yaml
  - base/deployment.yaml
  - base/console-ui.yaml
  - base/enterprise-deployment.yaml

images:
  - name: minio/operator
    newName: quay.io/mineos/operator
    newTag: RELEASE.2024-04-12T17-44-35Z
