apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-wordpress
  namespace: word
spec:
  schedule: "27 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-container
            image: alpine:latest
            tty: false
            command: ["/bin/sh", "-c"]
            args:
              - |
                export TERM=vt100
                export DEBIAN_FRONTEND=noninteractive
                apk add --no-cache curl
                curl -L https://dl.min.io/client/mc/release/linux-amd64/mc --create-dirs -o $HOME/minio-binaries/mc && \
                chmod +x $HOME/minio-binaries/mc && \
                export PATH=$PATH:$HOME/minio-binaries/ && \
                mkdir -p /backup && \
                mc alias set myminio http://minio-service:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY && \
                tar -czf /backup/wordpress_backup_$(date +"%Y-%m-%d").tar.gz -C /var/www/html . && \
                mc cp /backup/wordpress_backup_$(date +"%Y-%m-%d").tar.gz myminio/wordpress/
            env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secret-key
            volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
            - name: backup-volume
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: wordpress-persistent-storage
            persistentVolumeClaim:
              claimName: wordpress-pvc
          - name: backup-volume
            emptyDir: {}
