apiVersion: v1
kind: {{ .Values.kind.service }}
metadata:
  name: {{ .Values.redis.service }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.redis.name }}
