apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: word
spec:
  type: LoadBalancer
  ports:
    - name: minio-port
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: minio
