apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio-operator
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 30090
  type: NodePort
  selector:
    app: word-deploy
    version: v1
